Improve logging and debugging
cable-cr/cable pull request #38
Opened 2021-11-06 15:12 UTC by mjeffrey18

- [x] There was a lot of spec logic around logging, I guess it seemed like it made sense to remove that?
- [x] Provided developers was an example of how they can change the logging level.
- [x] Refactored a bunch of rescue statements around the code to log the rescued errors.
- [x] Refactored the base connection class type mounting method.
- [x] Added a debug_json method which can be exposed on any rest endpoint to ping and get stats on the current state of the server

Let me know what you guys think?

2021-11-06 23:12 UTC, jwoertink requested changes
Love it! You can just leave the version update off, and we can get everything merged in and updated all at once. The rest looks great to me! Thanks so much for doing this

2021-11-06 23:12 UTC, jwoertink commented on README.md
> +  end
this is nice!

2021-11-07 14:52 UTC, mjeffrey18 commented on src/cable.cr
> +  VERSION = "0.2.0"
sounds good!

2021-11-07 20:29 UTC, jwoertink approved these changes
Sweet!

2021-11-07 21:04 UTC, russ approved these changes

2021-11-11 15:52 UTC, mjeffrey18 commented
Hey @russ / @jwoertink whenever you're ready, we can go ahead and start merging the other branches, except this PR.
Once everything else has been merged I'll need to clean up everything on this PR to finalise the new release.

2021-11-11 16:19 UTC, jwoertink commented
Thanks for the heads up @mjeffrey18. Right now @fernandes is on vacation, but once he gets back, we should be good to start merging stuff in. 👍  Thanks so much for tackling this, it's huge!

2021-11-19 14:13 UTC, mjeffrey18 commented
@fernandes this one is ready for final review/merge

Big shout out again to @jgaskins as a lot of the inspiration for the cleanup came from his fork 💪

2021-11-19 15:45 UTC, jwoertink approved these changes
Thanks so much for this!

2021-11-19 15:45 UTC, merged

2021-11-19 16:23 UTC, fernandes commented
@mjeffrey18 what's the rational behind removing these messages? I'm asking because it helped me in the past to catch a few bugs lol

> There was a lot of spec logic around logging, I guess it seemed like it made sense to remove that?

maybe my first comment answers this one on description 😉 

if this is just because now we are using a bare crystal log class, it supports [capturing](https://crystal-lang.org/api/1.2.2/Log.html#capture%28source%3AString%3D%22%2A%22%2Clevel%3ASeverity%3DLog%3A%3ASeverity%3A%3ATrace%2C%2A%2Cbuilder%3DLog.builder%2C%26%29-class-method) the logs for testing, like I did [here](https://github.com/fernandes/caco/blob/9e0ff945afd1e706187cf0d0333327b6336495c4/spec/caco/rbenv_spec.cr#L80-L87)

2021-11-19 16:59 UTC, mjeffrey18 commented
Hey @fernandes, your right, logging can absolutely catch bugs. I've always found solid specs are way better at catching bugs and logs are better for debugging/monitoring.

Taking some lessons I've learned from heavy use of Rspec over the years;


- Testing if methods are called can leads to false positives and/or flaky specs.
- Use mutations/results should be tested where possible. This avoids flaky specs and focuses on outcomes over implementation.
- Logging is amazing for debugging, so unless the specs are weak (which they're not, you've done a pretty solid job!) we will catch bugs with specs.

However, I'm open to other alternative approaches (as your suggested) if we feel testing the logs is worth it for this particular case.

2021-11-22 13:23 UTC, fernandes commented
I agree, I tried to test the behavior as much as possible

> you've done a pretty solid job!

thank you! 🙇 

my final thought is if we should handle log messages as part as the software behavior/functionality, because if so, it's good to have it tested, once users will get the correct messages in the tested scenario

comments? 😄